spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    #    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true


camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: bhargava
      last-name: narendra
      email: admin@gmail.com
    authorization:
      enabled: true
      tenant-check-enabled: false
      enabled-for-custom-code: true
---
spring:
  config:
    activate:
      on-profile:
        - docker
  datasource:
    url: jdbc:h2:file:/usr/local/lib/camunda-h2-database
